name: CI Tests

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'lab2/**'
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - 'lab2/**'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [gcc, clang]
        exclude:
          - os: windows-latest
            compiler: clang  # Windows doesn't have clang by default
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgtest-dev
        echo "GTEST_INCLUDE_PATH=/usr/include/gtest" >> $GITHUB_ENV
        echo "GTEST_LIB_PATH=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV
        echo "Verifying Google Test installation:"
        ls -la /usr/include/gtest/
        ls -la /usr/lib/x86_64-linux-gnu/libgtest*
    
    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install googletest
        echo "GTEST_INCLUDE_PATH=/opt/homebrew/include" >> $GITHUB_ENV
        echo "GTEST_LIB_PATH=/opt/homebrew/lib" >> $GITHUB_ENV
    
    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        # Install vcpkg for Google Test
        git clone https://github.com/Microsoft/vcpkg.git C:\vcpkg
        C:\vcpkg\bootstrap-vcpkg.bat
        C:\vcpkg\vcpkg install gtest
        echo "GTEST_INCLUDE_PATH=C:\vcpkg\installed\x64-windows\include" >> $GITHUB_ENV
        echo "GTEST_LIB_PATH=C:\vcpkg\installed\x64-windows\lib" >> $GITHUB_ENV
    
    - name: Set up compiler (GCC)
      if: matrix.compiler == 'gcc'
      run: |
        if [ "$RUNNER_OS" = "Windows" ]; then
          echo "CXX=g++" >> $GITHUB_ENV
          echo "CC=gcc" >> $GITHUB_ENV
        else
          echo "CXX=g++" >> $GITHUB_ENV
          echo "CC=gcc" >> $GITHUB_ENV
        fi
    
    - name: Set up compiler (Clang)
      if: matrix.compiler == 'clang'
      run: |
        if [ "$RUNNER_OS" = "Windows" ]; then
          echo "CXX=clang++" >> $GITHUB_ENV
          echo "CC=clang" >> $GITHUB_ENV
        else
          echo "CXX=clang++" >> $GITHUB_ENV
          echo "CC=clang" >> $GITHUB_ENV
        fi
    
    - name: Build main game
      run: |
        cd lab2/game
        make clean
        make CXX=$CXX
    
    - name: Build and run tests
      run: |
        cd lab2/game/tests
        echo "Environment variables:"
        echo "GTEST_INCLUDE_PATH=$GTEST_INCLUDE_PATH"
        echo "GTEST_LIB_PATH=$GTEST_LIB_PATH"
        echo "CXX=$CXX"
        make clean
        make CXX=$CXX
        ./all_tests
    
    - name: Test game executable
      run: |
        cd lab2/game
        echo "help" | timeout 5s ./bin/game || true
    
    - name: Upload build artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.os }}-${{ matrix.compiler }}
        path: |
          lab2/game/bin/game
          lab2/game/tests/all_tests
