name: CI Tests

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'lab2/**'
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - 'lab2/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgtest-dev
        echo "GTEST_INCLUDE_PATH=/usr/include/gtest" >> $GITHUB_ENV
        echo "GTEST_LIB_PATH=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV
        echo "Verifying Google Test installation:"
        ls -la /usr/include/gtest/
        ls -la /usr/lib/x86_64-linux-gnu/libgtest*
    
    - name: Set up compiler
      run: |
        echo "CXX=g++" >> $GITHUB_ENV
        echo "CC=gcc" >> $GITHUB_ENV
    
    - name: Build main game
      run: |
        cd lab2/game
        make clean
        make CXX=$CXX
    
    - name: Build and run tests
      run: |
        cd lab2/game/tests
        echo "Environment variables:"
        echo "GTEST_INCLUDE_PATH=$GTEST_INCLUDE_PATH"
        echo "GTEST_LIB_PATH=$GTEST_LIB_PATH"
        echo "CXX=$CXX"
        make clean
        make CXX=$CXX
        ./all_tests
    
    - name: Test game executable
      run: |
        cd lab2/game
        echo "help" | timeout 5s ./bin/game || true
    
    - name: Upload build artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-ubuntu-gcc
        path: |
          lab2/game/bin/game
          lab2/game/tests/all_tests
