name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: [ main, develope ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make doxygen graphviz

    - name: Generate documentation
      run: |
        echo "Current directory: $(pwd)"
        echo "Checking if Doxyfile exists:"
        ls -la Doxyfile
        echo "Doxygen version:"
        doxygen --version
        doxygen Doxyfile

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/html

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4